import {
  Activity,
  BarChart3,
  BriefcaseBusiness,
  Bug,
  CloudLightning,
  Coins,
  Database,
  Factory,
  FlaskConical,
  LayoutDashboard,
  Leaf,
  PackageSearch,
  ShieldCheck,
  ShoppingBag,
  Sprout,
  Store,
  Tractor,
  Truck,
  Warehouse,
  Wallet,
  Wheat,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";
import type { EntityKey, WorkspaceId } from "@/lib/store/types";

const workspaceIconMap: Record<WorkspaceId, LucideIcon> = {
  farmer: Sprout,
  production: Factory,
  aggregation: Warehouse,
  marketplace: Store,
  logistics: Truck,
  finance: Wallet,
  weather: CloudLightning,
  prices: Activity,
  expert: BriefcaseBusiness,
  analytics: BarChart3,
  admin: ShieldCheck,
};

const entityIconMap: Record<EntityKey, LucideIcon> = {
  farmers: Tractor,
  farms: Wheat,
  plots: LayoutDashboard,
  crops: Leaf,
  inputs: PackageSearch,
  tasks: Activity,
  advisories: BriefcaseBusiness,
  weatherAlerts: CloudLightning,
  priceSignals: Activity,
  cropCycles: Sprout,
  growthStages: Activity,
  sensorReadings: Activity,
  pestIncidents: Bug,
  yieldPredictions: BarChart3,
  warehouses: Warehouse,
  storageBins: PackageSearch,
  batches: PackageSearch,
  qualityGrades: FlaskConical,
  stockMovements: Activity,
  spoilageReports: Bug,
  listings: ShoppingBag,
  rfqs: Store,
  orders: ShoppingBag,
  contracts: BriefcaseBusiness,
  negotiations: BriefcaseBusiness,
  reviews: Activity,
  shipments: Truck,
  routes: Truck,
  vehicles: Truck,
  drivers: Tractor,
  trackingEvents: Activity,
  coldChainLogs: Activity,
  wallets: Wallet,
  transactions: Coins,
  escrowAccounts: Wallet,
  payouts: Wallet,
  invoices: Coins,
  credits: Coins,
  insurancePolicies: ShieldCheck,
  stations: CloudLightning,
  forecasts: CloudLightning,
  alertRules: CloudLightning,
  commodities: Wheat,
  marketPrices: Coins,
  priceEstimations: BarChart3,
  pricePredictions: BarChart3,
  recommendations: Activity,
  marketSignals: Activity,
  dataSources: Database,
  knowledgeBaseArticles: BriefcaseBusiness,
  researchReports: FlaskConical,
  fieldCases: BriefcaseBusiness,
  assignments: Activity,
  reviewQueue: Activity,
  datasets: Database,
  charts: BarChart3,
  dashboards: LayoutDashboard,
  reports: BriefcaseBusiness,
  templates: LayoutDashboard,
  users: ShieldCheck,
  orgs: ShieldCheck,
  roles: ShieldCheck,
  permissions: ShieldCheck,
  apiTokens: ShieldCheck,
  moduleToggles: ShieldCheck,
};

export function getWorkspaceIcon(workspaceId: WorkspaceId): LucideIcon {
  return workspaceIconMap[workspaceId] ?? LayoutDashboard;
}

export function getEntityIcon(entityKey: EntityKey): LucideIcon {
  return entityIconMap[entityKey] ?? Activity;
}
