import type { EntityKey, WorkspaceId } from "@/lib/store/types";

export type ApiMethod = "GET" | "POST" | "PUT" | "PATCH" | "DELETE";

export interface ApiEndpointCatalogEntry {
  id: string;
  method: ApiMethod;
  path: string;
  summary: string;
  workspace: WorkspaceId;
  entityKey?: EntityKey;
  uiImplemented: boolean;
}

export const API_ENDPOINT_CATALOG: ApiEndpointCatalogEntry[] = [
  {
    id: "admin-super-admin-token-list",
    method: "GET",
    path: "/api/v1/auth/super-admin/tokens",
    summary: "List my Super Admin scoped tokens",
    workspace: "admin",
    entityKey: "apiTokens",
    uiImplemented: false,
  },
  {
    id: "admin-super-admin-token-create",
    method: "POST",
    path: "/api/v1/auth/super-admin/tokens",
    summary: "Create Super Admin scoped token",
    workspace: "admin",
    entityKey: "apiTokens",
    uiImplemented: false,
  },
  {
    id: "admin-super-admin-token-revoke",
    method: "DELETE",
    path: "/api/v1/auth/super-admin/tokens/{grantId}",
    summary: "Revoke Super Admin scoped token",
    workspace: "admin",
    entityKey: "apiTokens",
    uiImplemented: false,
  },
  {
    id: "admin-impersonation-list",
    method: "GET",
    path: "/api/v1/auth/super-admin/impersonation",
    summary: "List my impersonation sessions",
    workspace: "admin",
    uiImplemented: false,
  },
  {
    id: "admin-impersonation-start",
    method: "POST",
    path: "/api/v1/auth/super-admin/impersonation",
    summary: "Start user impersonation",
    workspace: "admin",
    uiImplemented: false,
  },
  {
    id: "admin-impersonation-revoke",
    method: "DELETE",
    path: "/api/v1/auth/super-admin/impersonation/{sessionId}",
    summary: "Revoke impersonation session",
    workspace: "admin",
    uiImplemented: false,
  },
  {
    id: "farmer-profile-verify",
    method: "POST",
    path: "/api/v1/farmers/profiles/{id}/verify",
    summary: "Verify or reject farmer profile",
    workspace: "farmer",
    entityKey: "farmers",
    uiImplemented: true,
  },
  {
    id: "farmer-membership-eligibility",
    method: "PATCH",
    path: "/api/v1/farmers/{farmerId}/membership/eligibility",
    summary: "Update service eligibility",
    workspace: "farmer",
    entityKey: "farmers",
    uiImplemented: false,
  },
  {
    id: "farmer-stats",
    method: "GET",
    path: "/api/v1/farmers/stats",
    summary: "Farmer module statistics",
    workspace: "farmer",
    entityKey: "farmers",
    uiImplemented: false,
  },
  {
    id: "dispute-resolve",
    method: "POST",
    path: "/api/v1/disputes/{id}/resolve",
    summary: "Resolve dispute",
    workspace: "marketplace",
    entityKey: "contracts",
    uiImplemented: true,
  },
  {
    id: "dispute-admin-list-all",
    method: "GET",
    path: "/api/v1/disputes/admin/all",
    summary: "List all disputes (admin)",
    workspace: "admin",
    entityKey: "contracts",
    uiImplemented: false,
  },
  {
    id: "dispute-admin-stats",
    method: "GET",
    path: "/api/v1/disputes/admin/stats",
    summary: "Get dispute statistics (admin)",
    workspace: "admin",
    entityKey: "contracts",
    uiImplemented: false,
  },
  {
    id: "dispute-admin-review",
    method: "POST",
    path: "/api/v1/disputes/{id}/review",
    summary: "Review dispute (admin note)",
    workspace: "admin",
    entityKey: "contracts",
    uiImplemented: false,
  },
  {
    id: "dispute-admin-assign-mediator",
    method: "POST",
    path: "/api/v1/disputes/{id}/mediator",
    summary: "Assign mediator to dispute",
    workspace: "admin",
    entityKey: "contracts",
    uiImplemented: false,
  },
  {
    id: "dispute-close",
    method: "POST",
    path: "/api/v1/disputes/{id}/close",
    summary: "Close dispute",
    workspace: "marketplace",
    entityKey: "contracts",
    uiImplemented: true,
  },
  {
    id: "notification-template-list",
    method: "GET",
    path: "/api/v1/notifications/templates",
    summary: "List notification templates",
    workspace: "admin",
    uiImplemented: true,
  },
  {
    id: "notification-template-create",
    method: "POST",
    path: "/api/v1/notifications/templates",
    summary: "Create notification template",
    workspace: "admin",
    uiImplemented: false,
  },
  {
    id: "notification-template-get",
    method: "GET",
    path: "/api/v1/notifications/templates/{id}",
    summary: "Get template by ID",
    workspace: "admin",
    uiImplemented: false,
  },
  {
    id: "notification-template-update",
    method: "PATCH",
    path: "/api/v1/notifications/templates/{id}",
    summary: "Update notification template",
    workspace: "admin",
    uiImplemented: false,
  },
  {
    id: "notification-template-delete",
    method: "DELETE",
    path: "/api/v1/notifications/templates/{id}",
    summary: "Delete notification template",
    workspace: "admin",
    uiImplemented: false,
  },
  {
    id: "notification-retry-failed",
    method: "POST",
    path: "/api/v1/notifications/admin/retry-failed",
    summary: "Retry failed notifications",
    workspace: "admin",
    uiImplemented: true,
  },
  {
    id: "notification-expire-old",
    method: "POST",
    path: "/api/v1/notifications/admin/expire-old",
    summary: "Expire old notifications",
    workspace: "admin",
    uiImplemented: true,
  },
  {
    id: "notification-template-seed",
    method: "POST",
    path: "/api/v1/notifications/templates/seed",
    summary: "Seed notification templates",
    workspace: "admin",
    uiImplemented: false,
  },
  {
    id: "prices-bulk-import",
    method: "POST",
    path: "/api/v1/prices/bulk-import",
    summary: "Bulk import prices",
    workspace: "prices",
    entityKey: "marketPrices",
    uiImplemented: false,
  },
  {
    id: "prices-update",
    method: "PUT",
    path: "/api/v1/prices/{id}",
    summary: "Update price entry",
    workspace: "prices",
    entityKey: "marketPrices",
    uiImplemented: false,
  },
  {
    id: "prices-delete",
    method: "DELETE",
    path: "/api/v1/prices/{id}",
    summary: "Delete price entry",
    workspace: "prices",
    entityKey: "marketPrices",
    uiImplemented: true,
  },
  {
    id: "prices-train-model",
    method: "POST",
    path: "/api/v1/pricing/train",
    summary: "Retrain price prediction model",
    workspace: "prices",
    entityKey: "pricePredictions",
    uiImplemented: false,
  },
  {
    id: "expert-verify",
    method: "POST",
    path: "/api/v1/expert-portal/experts/{id}/verify",
    summary: "Verify or reject expert application",
    workspace: "expert",
    uiImplemented: false,
  },
  {
    id: "expert-suspend",
    method: "POST",
    path: "/api/v1/expert-portal/experts/{id}/suspend",
    summary: "Suspend an expert",
    workspace: "expert",
    uiImplemented: false,
  },
  {
    id: "expert-ai-feedback",
    method: "GET",
    path: "/api/v1/expert-portal/cases/ai-feedback",
    summary: "Get AI model feedback data (ML pipeline)",
    workspace: "expert",
    uiImplemented: false,
  },
  {
    id: "expert-case-assign",
    method: "POST",
    path: "/api/v1/expert-portal/cases/{id}/assign",
    summary: "Assign case to an expert",
    workspace: "expert",
    entityKey: "fieldCases",
    uiImplemented: true,
  },
  {
    id: "expert-review-queue-approve",
    method: "POST",
    path: "/api/v1/expert-portal/review-queue/{id}/approve",
    summary: "Approve review queue item",
    workspace: "expert",
    entityKey: "reviewQueue",
    uiImplemented: true,
  },
  {
    id: "expert-review-queue-reject",
    method: "POST",
    path: "/api/v1/expert-portal/review-queue/{id}/reject",
    summary: "Reject review queue item",
    workspace: "expert",
    entityKey: "reviewQueue",
    uiImplemented: true,
  },
  {
    id: "expert-report-publish",
    method: "POST",
    path: "/api/v1/expert-portal/research-reports/{id}/publish",
    summary: "Publish research report",
    workspace: "expert",
    entityKey: "researchReports",
    uiImplemented: true,
  },
  {
    id: "expert-knowledge-review",
    method: "POST",
    path: "/api/v1/expert-portal/knowledge/{id}/review",
    summary: "Approve or reject article",
    workspace: "expert",
    entityKey: "knowledgeBaseArticles",
    uiImplemented: true,
  },
  {
    id: "expert-knowledge-publish",
    method: "POST",
    path: "/api/v1/expert-portal/knowledge/{id}/publish",
    summary: "Publish an approved article",
    workspace: "expert",
    entityKey: "knowledgeBaseArticles",
    uiImplemented: true,
  },
  {
    id: "expert-advisory-review",
    method: "POST",
    path: "/api/v1/expert-portal/advisories/{id}/review",
    summary: "Review advisory submission",
    workspace: "expert",
    entityKey: "advisories",
    uiImplemented: true,
  },
  {
    id: "expert-inquiries-unassigned",
    method: "GET",
    path: "/api/v1/expert-portal/inquiries/unassigned",
    summary: "Get open unassigned inquiries (admin triage)",
    workspace: "expert",
    entityKey: "fieldCases",
    uiImplemented: false,
  },
  {
    id: "expert-inquiry-assign",
    method: "POST",
    path: "/api/v1/expert-portal/inquiries/{id}/assign",
    summary: "Assign inquiry to an expert",
    workspace: "expert",
    entityKey: "fieldCases",
    uiImplemented: false,
  },
  {
    id: "weather-rule-create",
    method: "POST",
    path: "/api/v1/weather/rules",
    summary: "Create alert rule",
    workspace: "weather",
    entityKey: "alertRules",
    uiImplemented: true,
  },
  {
    id: "weather-rule-seed",
    method: "POST",
    path: "/api/v1/weather/rules/seed",
    summary: "Seed default alert rules",
    workspace: "weather",
    entityKey: "alertRules",
    uiImplemented: false,
  },
  {
    id: "weather-rule-update",
    method: "PATCH",
    path: "/api/v1/weather/rules/{id}",
    summary: "Update alert rule",
    workspace: "weather",
    entityKey: "alertRules",
    uiImplemented: true,
  },
  {
    id: "weather-rule-delete",
    method: "DELETE",
    path: "/api/v1/weather/rules/{id}",
    summary: "Delete alert rule",
    workspace: "weather",
    entityKey: "alertRules",
    uiImplemented: true,
  },
  {
    id: "weather-admin-refresh-all",
    method: "POST",
    path: "/api/v1/weather/admin/refresh",
    summary: "Refresh weather data for all profiles",
    workspace: "weather",
    entityKey: "stations",
    uiImplemented: true,
  },
  {
    id: "weather-admin-refresh-profile",
    method: "POST",
    path: "/api/v1/weather/admin/profiles/{profileId}/refresh",
    summary: "Manually refresh a single farm profile",
    workspace: "weather",
    entityKey: "stations",
    uiImplemented: true,
  },
  {
    id: "weather-admin-retry-deliveries",
    method: "POST",
    path: "/api/v1/weather/admin/retry-deliveries",
    summary: "Retry failed alert deliveries",
    workspace: "weather",
    entityKey: "stations",
    uiImplemented: true,
  },
  {
    id: "weather-admin-expire-alerts",
    method: "POST",
    path: "/api/v1/weather/admin/expire-alerts",
    summary: "Expire old weather alerts",
    workspace: "weather",
    entityKey: "stations",
    uiImplemented: true,
  },
  {
    id: "weather-admin-prune-snapshots",
    method: "POST",
    path: "/api/v1/weather/admin/prune-snapshots",
    summary: "Prune old condition snapshots",
    workspace: "weather",
    entityKey: "stations",
    uiImplemented: true,
  },
  {
    id: "weather-admin-provider-health",
    method: "GET",
    path: "/api/v1/weather/admin/providers",
    summary: "Get weather provider health status",
    workspace: "weather",
    entityKey: "dataSources",
    uiImplemented: true,
  },
  {
    id: "weather-admin-simulate-alert",
    method: "POST",
    path: "/api/v1/weather/admin/simulate",
    summary: "Simulate weather alert",
    workspace: "weather",
    uiImplemented: false,
  },
  {
    id: "audit-suspicious",
    method: "GET",
    path: "/api/v1/audit/suspicious",
    summary: "Get suspicious activity report",
    workspace: "admin",
    uiImplemented: false,
  },
  {
    id: "market-intelligence-alert-check",
    method: "POST",
    path: "/api/v1/market-intelligence/alerts/check",
    summary: "Trigger price alert check (admin/testing)",
    workspace: "prices",
    entityKey: "marketSignals",
    uiImplemented: false,
  },
  {
    id: "admin-org-list",
    method: "GET",
    path: "/api/v1/admin/organizations",
    summary: "List organizations (admin workspace)",
    workspace: "admin",
    entityKey: "orgs",
    uiImplemented: true,
  },
  {
    id: "admin-users-members-list",
    method: "GET",
    path: "/api/v1/organizations/{orgId}/members",
    summary: "List organization users",
    workspace: "admin",
    entityKey: "users",
    uiImplemented: true,
  },
  {
    id: "admin-users-members-create",
    method: "POST",
    path: "/api/v1/organizations/{orgId}/members/invite",
    summary: "Invite organization user",
    workspace: "admin",
    entityKey: "users",
    uiImplemented: true,
  },
  {
    id: "admin-users-members-update",
    method: "PATCH",
    path: "/api/v1/organizations/{orgId}/members/{id}/role",
    summary: "Update organization user role",
    workspace: "admin",
    entityKey: "users",
    uiImplemented: true,
  },
  {
    id: "admin-users-members-delete",
    method: "DELETE",
    path: "/api/v1/organizations/{orgId}/members/{id}",
    summary: "Remove organization user",
    workspace: "admin",
    entityKey: "users",
    uiImplemented: true,
  },
  {
    id: "admin-roles-list",
    method: "GET",
    path: "/api/v1/admin/roles",
    summary: "List roles",
    workspace: "admin",
    entityKey: "roles",
    uiImplemented: true,
  },
  {
    id: "admin-roles-create",
    method: "POST",
    path: "/api/v1/admin/roles",
    summary: "Create role",
    workspace: "admin",
    entityKey: "roles",
    uiImplemented: true,
  },
  {
    id: "admin-roles-get",
    method: "GET",
    path: "/api/v1/admin/roles/{roleId}",
    summary: "Get role",
    workspace: "admin",
    entityKey: "roles",
    uiImplemented: true,
  },
  {
    id: "admin-roles-update",
    method: "PATCH",
    path: "/api/v1/admin/roles/{roleId}",
    summary: "Update role",
    workspace: "admin",
    entityKey: "roles",
    uiImplemented: true,
  },
  {
    id: "admin-roles-delete",
    method: "DELETE",
    path: "/api/v1/admin/roles/{roleId}",
    summary: "Delete role",
    workspace: "admin",
    entityKey: "roles",
    uiImplemented: true,
  },
  {
    id: "admin-permissions-list",
    method: "GET",
    path: "/api/v1/admin/permissions",
    summary: "List permissions catalog",
    workspace: "admin",
    entityKey: "permissions",
    uiImplemented: true,
  },
  {
    id: "admin-permissions-create",
    method: "POST",
    path: "/api/v1/admin/permissions",
    summary: "Create permission",
    workspace: "admin",
    entityKey: "permissions",
    uiImplemented: true,
  },
  {
    id: "admin-permissions-get",
    method: "GET",
    path: "/api/v1/admin/permissions/{permissionId}",
    summary: "Get permission",
    workspace: "admin",
    entityKey: "permissions",
    uiImplemented: true,
  },
  {
    id: "admin-permissions-update",
    method: "PATCH",
    path: "/api/v1/admin/permissions/{permissionId}",
    summary: "Update permission",
    workspace: "admin",
    entityKey: "permissions",
    uiImplemented: true,
  },
  {
    id: "admin-permissions-delete",
    method: "DELETE",
    path: "/api/v1/admin/permissions/{permissionId}",
    summary: "Delete permission",
    workspace: "admin",
    entityKey: "permissions",
    uiImplemented: true,
  },
  {
    id: "admin-maintenance-get",
    method: "GET",
    path: "/api/v1/admin/system/maintenance",
    summary: "Get maintenance mode state",
    workspace: "admin",
    uiImplemented: false,
  },
  {
    id: "admin-maintenance-update",
    method: "PATCH",
    path: "/api/v1/admin/system/maintenance",
    summary: "Update maintenance mode",
    workspace: "admin",
    uiImplemented: false,
  },
  {
    id: "admin-feature-flags-get",
    method: "GET",
    path: "/api/v1/admin/system/feature-flags",
    summary: "Get feature flags",
    workspace: "admin",
    entityKey: "moduleToggles",
    uiImplemented: true,
  },
  {
    id: "admin-feature-flags-update",
    method: "PATCH",
    path: "/api/v1/admin/system/feature-flags",
    summary: "Update feature flags",
    workspace: "admin",
    entityKey: "moduleToggles",
    uiImplemented: true,
  },
  {
    id: "admin-feature-flags-workspace-get",
    method: "GET",
    path: "/api/v1/admin/system/feature-flags/{workspaceId}",
    summary: "Get workspace feature flag",
    workspace: "admin",
    entityKey: "moduleToggles",
    uiImplemented: false,
  },
  {
    id: "admin-feature-flags-workspace-update",
    method: "PATCH",
    path: "/api/v1/admin/system/feature-flags/{workspaceId}",
    summary: "Update workspace feature flag",
    workspace: "admin",
    entityKey: "moduleToggles",
    uiImplemented: false,
  },
  {
    id: "system-ready",
    method: "GET",
    path: "/api/v1/ready",
    summary: "Readiness probe",
    workspace: "admin",
    uiImplemented: false,
  },
  {
    id: "system-version",
    method: "GET",
    path: "/api/v1/version",
    summary: "Version metadata",
    workspace: "admin",
    uiImplemented: false,
  },
];

export function listWorkspaceEndpoints(workspaceId: WorkspaceId): ApiEndpointCatalogEntry[] {
  return API_ENDPOINT_CATALOG.filter((endpoint) => endpoint.workspace === workspaceId);
}

export function getWorkspaceEndpoint(workspaceId: WorkspaceId, endpointId: string): ApiEndpointCatalogEntry | undefined {
  return API_ENDPOINT_CATALOG.find((endpoint) => endpoint.workspace === workspaceId && endpoint.id === endpointId);
}

export function getWorkspaceEntityKeysFromEndpointCatalog(workspaceId: WorkspaceId): EntityKey[] {
  const unique = new Set<EntityKey>();
  const entityKeys: EntityKey[] = [];

  listWorkspaceEndpoints(workspaceId).forEach((endpoint) => {
    if (!endpoint.entityKey) return;
    if (unique.has(endpoint.entityKey)) return;
    unique.add(endpoint.entityKey);
    entityKeys.push(endpoint.entityKey);
  });

  return entityKeys;
}
