import type { EntityKey, WorkspaceId } from "@/lib/store/types";

export type ApiMethod = "GET" | "POST" | "PUT" | "PATCH" | "DELETE";

export interface ApiEndpointCatalogEntry {
  id: string;
  method: ApiMethod;
  path: string;
  summary: string;
  workspace: WorkspaceId;
  entityKey?: EntityKey;
  uiImplemented: boolean;
}

export const API_ENDPOINT_CATALOG: ApiEndpointCatalogEntry[] = [
  {
    id: "admin-super-admin-token-list",
    method: "GET",
    path: "/api/v1/auth/super-admin/tokens",
    summary: "List my Super Admin scoped tokens",
    workspace: "admin",
    entityKey: "apiTokens",
    uiImplemented: false,
  },
  {
    id: "admin-super-admin-token-create",
    method: "POST",
    path: "/api/v1/auth/super-admin/tokens",
    summary: "Create Super Admin scoped token",
    workspace: "admin",
    entityKey: "apiTokens",
    uiImplemented: false,
  },
  {
    id: "admin-super-admin-token-revoke",
    method: "DELETE",
    path: "/api/v1/auth/super-admin/tokens/{grantId}",
    summary: "Revoke Super Admin scoped token",
    workspace: "admin",
    entityKey: "apiTokens",
    uiImplemented: false,
  },
  {
    id: "admin-impersonation-list",
    method: "GET",
    path: "/api/v1/auth/super-admin/impersonation",
    summary: "List my impersonation sessions",
    workspace: "admin",
    uiImplemented: false,
  },
  {
    id: "admin-impersonation-start",
    method: "POST",
    path: "/api/v1/auth/super-admin/impersonation",
    summary: "Start user impersonation",
    workspace: "admin",
    uiImplemented: false,
  },
  {
    id: "admin-impersonation-revoke",
    method: "DELETE",
    path: "/api/v1/auth/super-admin/impersonation/{sessionId}",
    summary: "Revoke impersonation session",
    workspace: "admin",
    uiImplemented: false,
  },
  {
    id: "farmer-profile-create",
    method: "POST",
    path: "/api/v1/farmers/profiles",
    summary: "Create farmer profile",
    workspace: "farmer",
    entityKey: "farmers",
    uiImplemented: true,
  },
  {
    id: "farmer-profile-list",
    method: "GET",
    path: "/api/v1/farmers/profiles",
    summary: "List farmer profiles",
    workspace: "farmer",
    entityKey: "farmers",
    uiImplemented: true,
  },
  {
    id: "farmer-profile-me",
    method: "GET",
    path: "/api/v1/farmers/profiles/me",
    summary: "Get my farmer profile",
    workspace: "farmer",
    entityKey: "farmers",
    uiImplemented: true,
  },
  {
    id: "farmer-profile-get",
    method: "GET",
    path: "/api/v1/farmers/profiles/{id}",
    summary: "Get farmer profile by ID",
    workspace: "farmer",
    entityKey: "farmers",
    uiImplemented: true,
  },
  {
    id: "farmer-profile-update",
    method: "PATCH",
    path: "/api/v1/farmers/profiles/{id}",
    summary: "Update farmer profile",
    workspace: "farmer",
    entityKey: "farmers",
    uiImplemented: true,
  },
  {
    id: "farmer-profile-delete",
    method: "DELETE",
    path: "/api/v1/farmers/profiles/{id}",
    summary: "Soft-delete farmer profile",
    workspace: "farmer",
    entityKey: "farmers",
    uiImplemented: true,
  },
  {
    id: "farmer-profile-submit-verification",
    method: "POST",
    path: "/api/v1/farmers/profiles/{id}/verify/submit",
    summary: "Submit profile for verification",
    workspace: "farmer",
    entityKey: "farmers",
    uiImplemented: true,
  },
  {
    id: "farmer-profile-verify",
    method: "POST",
    path: "/api/v1/farmers/profiles/{id}/verify",
    summary: "Verify or reject farmer profile",
    workspace: "farmer",
    entityKey: "farmers",
    uiImplemented: true,
  },
  {
    id: "farmer-farm-create",
    method: "POST",
    path: "/api/v1/farmers/{farmerId}/farms",
    summary: "Create a farm for a farmer",
    workspace: "farmer",
    entityKey: "farms",
    uiImplemented: true,
  },
  {
    id: "farmer-farm-list",
    method: "GET",
    path: "/api/v1/farmers/{farmerId}/farms",
    summary: "Get farms for a farmer",
    workspace: "farmer",
    entityKey: "farms",
    uiImplemented: true,
  },
  {
    id: "farmer-farm-get",
    method: "GET",
    path: "/api/v1/farmers/farms/{farmId}",
    summary: "Get farm by ID",
    workspace: "farmer",
    entityKey: "farms",
    uiImplemented: false,
  },
  {
    id: "farmer-farm-update",
    method: "PATCH",
    path: "/api/v1/farmers/farms/{farmId}",
    summary: "Update farm details",
    workspace: "farmer",
    entityKey: "farms",
    uiImplemented: true,
  },
  {
    id: "farmer-farm-delete",
    method: "DELETE",
    path: "/api/v1/farmers/farms/{farmId}",
    summary: "Soft delete farm",
    workspace: "farmer",
    entityKey: "farms",
    uiImplemented: false,
  },
  {
    id: "farmer-plot-list",
    method: "GET",
    path: "/api/v1/farmers/{farmerId}/plots",
    summary: "List plots for farmer",
    workspace: "farmer",
    entityKey: "plots",
    uiImplemented: false,
  },
  {
    id: "farmer-plot-create",
    method: "POST",
    path: "/api/v1/farmers/{farmerId}/plots",
    summary: "Create plot for farmer",
    workspace: "farmer",
    entityKey: "plots",
    uiImplemented: false,
  },
  {
    id: "farmer-plot-get",
    method: "GET",
    path: "/api/v1/farmers/plots/{plotId}",
    summary: "Get plot by ID",
    workspace: "farmer",
    entityKey: "plots",
    uiImplemented: false,
  },
  {
    id: "farmer-plot-update",
    method: "PATCH",
    path: "/api/v1/farmers/plots/{plotId}",
    summary: "Update plot",
    workspace: "farmer",
    entityKey: "plots",
    uiImplemented: false,
  },
  {
    id: "farmer-plot-delete",
    method: "DELETE",
    path: "/api/v1/farmers/plots/{plotId}",
    summary: "Soft delete plot",
    workspace: "farmer",
    entityKey: "plots",
    uiImplemented: false,
  },
  {
    id: "farmer-production-crop-list",
    method: "GET",
    path: "/api/v1/farmers/{farmerId}/production/crops",
    summary: "List crop production records",
    workspace: "farmer",
    entityKey: "crops",
    uiImplemented: true,
  },
  {
    id: "farmer-production-crop-create",
    method: "POST",
    path: "/api/v1/farmers/{farmerId}/production/crops",
    summary: "Record crop production",
    workspace: "farmer",
    entityKey: "crops",
    uiImplemented: true,
  },
  {
    id: "farmer-production-crop-get",
    method: "GET",
    path: "/api/v1/farmers/production/crops/{cropId}",
    summary: "Get crop production by ID",
    workspace: "farmer",
    entityKey: "crops",
    uiImplemented: true,
  },
  {
    id: "farmer-production-crop-update",
    method: "PATCH",
    path: "/api/v1/farmers/production/crops/{cropId}",
    summary: "Update crop production",
    workspace: "farmer",
    entityKey: "crops",
    uiImplemented: true,
  },
  {
    id: "farmer-production-crop-delete",
    method: "DELETE",
    path: "/api/v1/farmers/production/crops/{cropId}",
    summary: "Soft delete crop production",
    workspace: "farmer",
    entityKey: "crops",
    uiImplemented: true,
  },
  {
    id: "farmer-growth-stage-list",
    method: "GET",
    path: "/api/v1/farmers/{farmerId}/production/growth-stages",
    summary: "List growth stages for a farmer",
    workspace: "farmer",
    entityKey: "growthStages",
    uiImplemented: false,
  },
  {
    id: "farmer-growth-stage-create",
    method: "POST",
    path: "/api/v1/farmers/{farmerId}/production/growth-stages",
    summary: "Create growth stage for a farmer",
    workspace: "farmer",
    entityKey: "growthStages",
    uiImplemented: false,
  },
  {
    id: "farmer-growth-stage-get",
    method: "GET",
    path: "/api/v1/farmers/production/growth-stages/{stageId}",
    summary: "Get growth stage by ID",
    workspace: "farmer",
    entityKey: "growthStages",
    uiImplemented: false,
  },
  {
    id: "farmer-growth-stage-update",
    method: "PATCH",
    path: "/api/v1/farmers/production/growth-stages/{stageId}",
    summary: "Update growth stage",
    workspace: "farmer",
    entityKey: "growthStages",
    uiImplemented: false,
  },
  {
    id: "farmer-growth-stage-delete",
    method: "DELETE",
    path: "/api/v1/farmers/production/growth-stages/{stageId}",
    summary: "Soft delete growth stage",
    workspace: "farmer",
    entityKey: "growthStages",
    uiImplemented: false,
  },
  {
    id: "farmer-yield-prediction-list",
    method: "GET",
    path: "/api/v1/farmers/{farmerId}/production/yield-predictions",
    summary: "List yield predictions for a farmer",
    workspace: "farmer",
    entityKey: "yieldPredictions",
    uiImplemented: false,
  },
  {
    id: "farmer-yield-prediction-create",
    method: "POST",
    path: "/api/v1/farmers/{farmerId}/production/yield-predictions",
    summary: "Create yield prediction for a farmer",
    workspace: "farmer",
    entityKey: "yieldPredictions",
    uiImplemented: false,
  },
  {
    id: "farmer-yield-prediction-get",
    method: "GET",
    path: "/api/v1/farmers/production/yield-predictions/{predictionId}",
    summary: "Get yield prediction by ID",
    workspace: "farmer",
    entityKey: "yieldPredictions",
    uiImplemented: false,
  },
  {
    id: "farmer-yield-prediction-update",
    method: "PATCH",
    path: "/api/v1/farmers/production/yield-predictions/{predictionId}",
    summary: "Update yield prediction",
    workspace: "farmer",
    entityKey: "yieldPredictions",
    uiImplemented: false,
  },
  {
    id: "farmer-yield-prediction-delete",
    method: "DELETE",
    path: "/api/v1/farmers/production/yield-predictions/{predictionId}",
    summary: "Soft delete yield prediction",
    workspace: "farmer",
    entityKey: "yieldPredictions",
    uiImplemented: false,
  },
  {
    id: "farmer-yield-prediction-refresh",
    method: "POST",
    path: "/api/v1/farmers/production/yield-predictions/{predictionId}/refresh",
    summary: "Refresh yield prediction",
    workspace: "farmer",
    entityKey: "yieldPredictions",
    uiImplemented: false,
  },
  {
    id: "farmer-livestock-production-record",
    method: "POST",
    path: "/api/v1/farmers/{farmerId}/production/livestock",
    summary: "Record livestock production",
    workspace: "farmer",
    uiImplemented: false,
  },
  {
    id: "farmer-production-history-combined",
    method: "GET",
    path: "/api/v1/farmers/{farmerId}/production",
    summary: "Get combined production history",
    workspace: "farmer",
    uiImplemented: true,
  },
  {
    id: "farmer-input-list",
    method: "GET",
    path: "/api/v1/farmers/{farmerId}/inputs",
    summary: "List farmer inputs",
    workspace: "farmer",
    entityKey: "inputs",
    uiImplemented: false,
  },
  {
    id: "farmer-input-create",
    method: "POST",
    path: "/api/v1/farmers/{farmerId}/inputs",
    summary: "Create farmer input record",
    workspace: "farmer",
    entityKey: "inputs",
    uiImplemented: false,
  },
  {
    id: "farmer-input-get",
    method: "GET",
    path: "/api/v1/farmers/inputs/{inputId}",
    summary: "Get input by ID",
    workspace: "farmer",
    entityKey: "inputs",
    uiImplemented: false,
  },
  {
    id: "farmer-input-update",
    method: "PATCH",
    path: "/api/v1/farmers/inputs/{inputId}",
    summary: "Update input",
    workspace: "farmer",
    entityKey: "inputs",
    uiImplemented: false,
  },
  {
    id: "farmer-input-delete",
    method: "DELETE",
    path: "/api/v1/farmers/inputs/{inputId}",
    summary: "Soft delete input",
    workspace: "farmer",
    entityKey: "inputs",
    uiImplemented: false,
  },
  {
    id: "farmer-membership-join-organization",
    method: "POST",
    path: "/api/v1/farmers/{farmerId}/membership/join-organization",
    summary: "Join an organization/cooperative",
    workspace: "farmer",
    entityKey: "farmers",
    uiImplemented: false,
  },
  {
    id: "farmer-membership-leave-organization",
    method: "POST",
    path: "/api/v1/farmers/{farmerId}/membership/leave-organization",
    summary: "Leave current organization",
    workspace: "farmer",
    entityKey: "farmers",
    uiImplemented: false,
  },
  {
    id: "farmer-membership-eligibility",
    method: "PATCH",
    path: "/api/v1/farmers/{farmerId}/membership/eligibility",
    summary: "Update service eligibility",
    workspace: "farmer",
    entityKey: "farmers",
    uiImplemented: false,
  },
  {
    id: "farmer-stats",
    method: "GET",
    path: "/api/v1/farmers/stats",
    summary: "Farmer module statistics",
    workspace: "farmer",
    entityKey: "farmers",
    uiImplemented: false,
  },
  {
    id: "farmer-legacy-list",
    method: "GET",
    path: "/api/v1/farmers/legacy",
    summary: "[Legacy] List all farmers",
    workspace: "farmer",
    entityKey: "farmers",
    uiImplemented: false,
  },
  {
    id: "farmer-legacy-create",
    method: "POST",
    path: "/api/v1/farmers/legacy",
    summary: "[Legacy] Create farmer profile",
    workspace: "farmer",
    entityKey: "farmers",
    uiImplemented: false,
  },
  {
    id: "farmer-legacy-me",
    method: "GET",
    path: "/api/v1/farmers/legacy/me",
    summary: "[Legacy] Get my farmer profile",
    workspace: "farmer",
    entityKey: "farmers",
    uiImplemented: false,
  },
  {
    id: "farmer-legacy-get",
    method: "GET",
    path: "/api/v1/farmers/legacy/{id}",
    summary: "[Legacy] Get farmer by ID",
    workspace: "farmer",
    entityKey: "farmers",
    uiImplemented: false,
  },
  {
    id: "farmer-legacy-update",
    method: "PUT",
    path: "/api/v1/farmers/legacy/{id}",
    summary: "[Legacy] Update farmer profile",
    workspace: "farmer",
    entityKey: "farmers",
    uiImplemented: false,
  },
  {
    id: "farmer-legacy-farm-create",
    method: "POST",
    path: "/api/v1/farmers/legacy/farms",
    summary: "[Legacy] Create a farm",
    workspace: "farmer",
    entityKey: "farms",
    uiImplemented: false,
  },
  {
    id: "farmer-legacy-farm-get",
    method: "GET",
    path: "/api/v1/farmers/legacy/farms/{id}",
    summary: "[Legacy] Get farm by ID",
    workspace: "farmer",
    entityKey: "farms",
    uiImplemented: false,
  },
  {
    id: "farmer-legacy-farm-update",
    method: "PUT",
    path: "/api/v1/farmers/legacy/farms/{id}",
    summary: "[Legacy] Update farm",
    workspace: "farmer",
    entityKey: "farms",
    uiImplemented: false,
  },
  {
    id: "farmer-legacy-farm-delete",
    method: "DELETE",
    path: "/api/v1/farmers/legacy/farms/{id}",
    summary: "[Legacy] Delete farm",
    workspace: "farmer",
    entityKey: "farms",
    uiImplemented: false,
  },
  {
    id: "farmer-legacy-farm-list-by-farmer",
    method: "GET",
    path: "/api/v1/farmers/legacy/{farmerId}/farms",
    summary: "[Legacy] Get all farms for a farmer",
    workspace: "farmer",
    entityKey: "farms",
    uiImplemented: false,
  },
  {
    id: "dispute-resolve",
    method: "POST",
    path: "/api/v1/disputes/{id}/resolve",
    summary: "Resolve dispute",
    workspace: "marketplace",
    entityKey: "contracts",
    uiImplemented: true,
  },
  {
    id: "dispute-admin-list-all",
    method: "GET",
    path: "/api/v1/disputes/admin/all",
    summary: "List all disputes (admin)",
    workspace: "admin",
    entityKey: "contracts",
    uiImplemented: false,
  },
  {
    id: "dispute-admin-stats",
    method: "GET",
    path: "/api/v1/disputes/admin/stats",
    summary: "Get dispute statistics (admin)",
    workspace: "admin",
    entityKey: "contracts",
    uiImplemented: false,
  },
  {
    id: "dispute-admin-review",
    method: "POST",
    path: "/api/v1/disputes/{id}/review",
    summary: "Review dispute (admin note)",
    workspace: "admin",
    entityKey: "contracts",
    uiImplemented: false,
  },
  {
    id: "dispute-admin-assign-mediator",
    method: "POST",
    path: "/api/v1/disputes/{id}/mediator",
    summary: "Assign mediator to dispute",
    workspace: "admin",
    entityKey: "contracts",
    uiImplemented: false,
  },
  {
    id: "dispute-close",
    method: "POST",
    path: "/api/v1/disputes/{id}/close",
    summary: "Close dispute",
    workspace: "marketplace",
    entityKey: "contracts",
    uiImplemented: true,
  },
  {
    id: "notification-template-list",
    method: "GET",
    path: "/api/v1/notifications/templates",
    summary: "List notification templates",
    workspace: "admin",
    uiImplemented: true,
  },
  {
    id: "notification-template-create",
    method: "POST",
    path: "/api/v1/notifications/templates",
    summary: "Create notification template",
    workspace: "admin",
    uiImplemented: false,
  },
  {
    id: "notification-template-get",
    method: "GET",
    path: "/api/v1/notifications/templates/{id}",
    summary: "Get template by ID",
    workspace: "admin",
    uiImplemented: false,
  },
  {
    id: "notification-template-update",
    method: "PATCH",
    path: "/api/v1/notifications/templates/{id}",
    summary: "Update notification template",
    workspace: "admin",
    uiImplemented: false,
  },
  {
    id: "notification-template-delete",
    method: "DELETE",
    path: "/api/v1/notifications/templates/{id}",
    summary: "Delete notification template",
    workspace: "admin",
    uiImplemented: false,
  },
  {
    id: "notification-retry-failed",
    method: "POST",
    path: "/api/v1/notifications/admin/retry-failed",
    summary: "Retry failed notifications",
    workspace: "admin",
    uiImplemented: true,
  },
  {
    id: "notification-expire-old",
    method: "POST",
    path: "/api/v1/notifications/admin/expire-old",
    summary: "Expire old notifications",
    workspace: "admin",
    uiImplemented: true,
  },
  {
    id: "notification-template-seed",
    method: "POST",
    path: "/api/v1/notifications/templates/seed",
    summary: "Seed notification templates",
    workspace: "admin",
    uiImplemented: false,
  },
  {
    id: "prices-bulk-import",
    method: "POST",
    path: "/api/v1/prices/bulk-import",
    summary: "Bulk import prices",
    workspace: "prices",
    entityKey: "marketPrices",
    uiImplemented: false,
  },
  {
    id: "prices-update",
    method: "PUT",
    path: "/api/v1/prices/{id}",
    summary: "Update price entry",
    workspace: "prices",
    entityKey: "marketPrices",
    uiImplemented: false,
  },
  {
    id: "prices-delete",
    method: "DELETE",
    path: "/api/v1/prices/{id}",
    summary: "Delete price entry",
    workspace: "prices",
    entityKey: "marketPrices",
    uiImplemented: true,
  },
  {
    id: "prices-train-model",
    method: "POST",
    path: "/api/v1/pricing/train",
    summary: "Retrain price prediction model",
    workspace: "prices",
    entityKey: "pricePredictions",
    uiImplemented: false,
  },
  {
    id: "expert-verify",
    method: "POST",
    path: "/api/v1/expert-portal/experts/{id}/verify",
    summary: "Verify or reject expert application",
    workspace: "expert",
    uiImplemented: false,
  },
  {
    id: "expert-suspend",
    method: "POST",
    path: "/api/v1/expert-portal/experts/{id}/suspend",
    summary: "Suspend an expert",
    workspace: "expert",
    uiImplemented: false,
  },
  {
    id: "expert-ai-feedback",
    method: "GET",
    path: "/api/v1/expert-portal/cases/ai-feedback",
    summary: "Get AI model feedback data (ML pipeline)",
    workspace: "expert",
    uiImplemented: false,
  },
  {
    id: "expert-case-assign",
    method: "POST",
    path: "/api/v1/expert-portal/cases/{id}/assign",
    summary: "Assign case to an expert",
    workspace: "expert",
    entityKey: "fieldCases",
    uiImplemented: true,
  },
  {
    id: "expert-review-queue-approve",
    method: "POST",
    path: "/api/v1/expert-portal/review-queue/{id}/approve",
    summary: "Approve review queue item",
    workspace: "expert",
    entityKey: "reviewQueue",
    uiImplemented: true,
  },
  {
    id: "expert-review-queue-reject",
    method: "POST",
    path: "/api/v1/expert-portal/review-queue/{id}/reject",
    summary: "Reject review queue item",
    workspace: "expert",
    entityKey: "reviewQueue",
    uiImplemented: true,
  },
  {
    id: "expert-report-publish",
    method: "POST",
    path: "/api/v1/expert-portal/research-reports/{id}/publish",
    summary: "Publish research report",
    workspace: "expert",
    entityKey: "researchReports",
    uiImplemented: true,
  },
  {
    id: "expert-knowledge-review",
    method: "POST",
    path: "/api/v1/expert-portal/knowledge/{id}/review",
    summary: "Approve or reject article",
    workspace: "expert",
    entityKey: "knowledgeBaseArticles",
    uiImplemented: true,
  },
  {
    id: "expert-knowledge-publish",
    method: "POST",
    path: "/api/v1/expert-portal/knowledge/{id}/publish",
    summary: "Publish an approved article",
    workspace: "expert",
    entityKey: "knowledgeBaseArticles",
    uiImplemented: true,
  },
  {
    id: "expert-advisory-review",
    method: "POST",
    path: "/api/v1/expert-portal/advisories/{id}/review",
    summary: "Review advisory submission",
    workspace: "expert",
    entityKey: "advisories",
    uiImplemented: true,
  },
  {
    id: "expert-inquiries-unassigned",
    method: "GET",
    path: "/api/v1/expert-portal/inquiries/unassigned",
    summary: "Get open unassigned inquiries (admin triage)",
    workspace: "expert",
    entityKey: "fieldCases",
    uiImplemented: false,
  },
  {
    id: "expert-inquiry-assign",
    method: "POST",
    path: "/api/v1/expert-portal/inquiries/{id}/assign",
    summary: "Assign inquiry to an expert",
    workspace: "expert",
    entityKey: "fieldCases",
    uiImplemented: false,
  },
  {
    id: "weather-rule-create",
    method: "POST",
    path: "/api/v1/weather/rules",
    summary: "Create alert rule",
    workspace: "weather",
    entityKey: "alertRules",
    uiImplemented: true,
  },
  {
    id: "weather-rule-seed",
    method: "POST",
    path: "/api/v1/weather/rules/seed",
    summary: "Seed default alert rules",
    workspace: "weather",
    entityKey: "alertRules",
    uiImplemented: false,
  },
  {
    id: "weather-rule-update",
    method: "PATCH",
    path: "/api/v1/weather/rules/{id}",
    summary: "Update alert rule",
    workspace: "weather",
    entityKey: "alertRules",
    uiImplemented: true,
  },
  {
    id: "weather-rule-delete",
    method: "DELETE",
    path: "/api/v1/weather/rules/{id}",
    summary: "Delete alert rule",
    workspace: "weather",
    entityKey: "alertRules",
    uiImplemented: true,
  },
  {
    id: "weather-admin-refresh-all",
    method: "POST",
    path: "/api/v1/weather/admin/refresh",
    summary: "Refresh weather data for all profiles",
    workspace: "weather",
    entityKey: "stations",
    uiImplemented: true,
  },
  {
    id: "weather-admin-refresh-profile",
    method: "POST",
    path: "/api/v1/weather/admin/profiles/{profileId}/refresh",
    summary: "Manually refresh a single farm profile",
    workspace: "weather",
    entityKey: "stations",
    uiImplemented: true,
  },
  {
    id: "weather-admin-retry-deliveries",
    method: "POST",
    path: "/api/v1/weather/admin/retry-deliveries",
    summary: "Retry failed alert deliveries",
    workspace: "weather",
    entityKey: "stations",
    uiImplemented: true,
  },
  {
    id: "weather-admin-expire-alerts",
    method: "POST",
    path: "/api/v1/weather/admin/expire-alerts",
    summary: "Expire old weather alerts",
    workspace: "weather",
    entityKey: "stations",
    uiImplemented: true,
  },
  {
    id: "weather-admin-prune-snapshots",
    method: "POST",
    path: "/api/v1/weather/admin/prune-snapshots",
    summary: "Prune old condition snapshots",
    workspace: "weather",
    entityKey: "stations",
    uiImplemented: true,
  },
  {
    id: "weather-admin-provider-health",
    method: "GET",
    path: "/api/v1/weather/admin/providers",
    summary: "Get weather provider health status",
    workspace: "weather",
    entityKey: "dataSources",
    uiImplemented: true,
  },
  {
    id: "weather-admin-simulate-alert",
    method: "POST",
    path: "/api/v1/weather/admin/simulate",
    summary: "Simulate weather alert",
    workspace: "weather",
    uiImplemented: false,
  },
  {
    id: "audit-suspicious",
    method: "GET",
    path: "/api/v1/audit/suspicious",
    summary: "Get suspicious activity report",
    workspace: "admin",
    uiImplemented: false,
  },
  {
    id: "market-intelligence-alert-check",
    method: "POST",
    path: "/api/v1/market-intelligence/alerts/check",
    summary: "Trigger price alert check (admin/testing)",
    workspace: "prices",
    entityKey: "marketSignals",
    uiImplemented: false,
  },
  {
    id: "admin-org-list",
    method: "GET",
    path: "/api/v1/admin/organizations",
    summary: "List organizations (admin workspace)",
    workspace: "admin",
    entityKey: "orgs",
    uiImplemented: true,
  },
  {
    id: "admin-users-members-list",
    method: "GET",
    path: "/api/v1/organizations/{orgId}/members",
    summary: "List organization users",
    workspace: "admin",
    entityKey: "users",
    uiImplemented: true,
  },
  {
    id: "admin-users-members-create",
    method: "POST",
    path: "/api/v1/organizations/{orgId}/members/invite",
    summary: "Invite organization user",
    workspace: "admin",
    entityKey: "users",
    uiImplemented: true,
  },
  {
    id: "admin-users-members-update",
    method: "PATCH",
    path: "/api/v1/organizations/{orgId}/members/{id}/role",
    summary: "Update organization user role",
    workspace: "admin",
    entityKey: "users",
    uiImplemented: true,
  },
  {
    id: "admin-users-members-delete",
    method: "DELETE",
    path: "/api/v1/organizations/{orgId}/members/{id}",
    summary: "Remove organization user",
    workspace: "admin",
    entityKey: "users",
    uiImplemented: true,
  },
  {
    id: "admin-roles-list",
    method: "GET",
    path: "/api/v1/admin/roles",
    summary: "List roles",
    workspace: "admin",
    entityKey: "roles",
    uiImplemented: true,
  },
  {
    id: "admin-roles-create",
    method: "POST",
    path: "/api/v1/admin/roles",
    summary: "Create role",
    workspace: "admin",
    entityKey: "roles",
    uiImplemented: true,
  },
  {
    id: "admin-roles-get",
    method: "GET",
    path: "/api/v1/admin/roles/{roleId}",
    summary: "Get role",
    workspace: "admin",
    entityKey: "roles",
    uiImplemented: true,
  },
  {
    id: "admin-roles-update",
    method: "PATCH",
    path: "/api/v1/admin/roles/{roleId}",
    summary: "Update role",
    workspace: "admin",
    entityKey: "roles",
    uiImplemented: true,
  },
  {
    id: "admin-roles-delete",
    method: "DELETE",
    path: "/api/v1/admin/roles/{roleId}",
    summary: "Delete role",
    workspace: "admin",
    entityKey: "roles",
    uiImplemented: true,
  },
  {
    id: "admin-permissions-list",
    method: "GET",
    path: "/api/v1/admin/permissions",
    summary: "List permissions catalog",
    workspace: "admin",
    entityKey: "permissions",
    uiImplemented: true,
  },
  {
    id: "admin-permissions-create",
    method: "POST",
    path: "/api/v1/admin/permissions",
    summary: "Create permission",
    workspace: "admin",
    entityKey: "permissions",
    uiImplemented: true,
  },
  {
    id: "admin-permissions-get",
    method: "GET",
    path: "/api/v1/admin/permissions/{permissionId}",
    summary: "Get permission",
    workspace: "admin",
    entityKey: "permissions",
    uiImplemented: true,
  },
  {
    id: "admin-permissions-update",
    method: "PATCH",
    path: "/api/v1/admin/permissions/{permissionId}",
    summary: "Update permission",
    workspace: "admin",
    entityKey: "permissions",
    uiImplemented: true,
  },
  {
    id: "admin-permissions-delete",
    method: "DELETE",
    path: "/api/v1/admin/permissions/{permissionId}",
    summary: "Delete permission",
    workspace: "admin",
    entityKey: "permissions",
    uiImplemented: true,
  },
  {
    id: "admin-maintenance-get",
    method: "GET",
    path: "/api/v1/admin/system/maintenance",
    summary: "Get maintenance mode state",
    workspace: "admin",
    uiImplemented: false,
  },
  {
    id: "admin-maintenance-update",
    method: "PATCH",
    path: "/api/v1/admin/system/maintenance",
    summary: "Update maintenance mode",
    workspace: "admin",
    uiImplemented: false,
  },
  {
    id: "admin-feature-flags-get",
    method: "GET",
    path: "/api/v1/admin/system/feature-flags",
    summary: "Get feature flags",
    workspace: "admin",
    entityKey: "moduleToggles",
    uiImplemented: true,
  },
  {
    id: "admin-feature-flags-update",
    method: "PATCH",
    path: "/api/v1/admin/system/feature-flags",
    summary: "Update feature flags",
    workspace: "admin",
    entityKey: "moduleToggles",
    uiImplemented: true,
  },
  {
    id: "admin-feature-flags-workspace-get",
    method: "GET",
    path: "/api/v1/admin/system/feature-flags/{workspaceId}",
    summary: "Get workspace feature flag",
    workspace: "admin",
    entityKey: "moduleToggles",
    uiImplemented: false,
  },
  {
    id: "admin-feature-flags-workspace-update",
    method: "PATCH",
    path: "/api/v1/admin/system/feature-flags/{workspaceId}",
    summary: "Update workspace feature flag",
    workspace: "admin",
    entityKey: "moduleToggles",
    uiImplemented: false,
  },
  {
    id: "system-ready",
    method: "GET",
    path: "/api/v1/ready",
    summary: "Readiness probe",
    workspace: "admin",
    uiImplemented: false,
  },
  {
    id: "system-version",
    method: "GET",
    path: "/api/v1/version",
    summary: "Version metadata",
    workspace: "admin",
    uiImplemented: false,
  },
];

export function listWorkspaceEndpoints(workspaceId: WorkspaceId): ApiEndpointCatalogEntry[] {
  return API_ENDPOINT_CATALOG.filter((endpoint) => endpoint.workspace === workspaceId);
}

export function getWorkspaceEndpoint(workspaceId: WorkspaceId, endpointId: string): ApiEndpointCatalogEntry | undefined {
  return API_ENDPOINT_CATALOG.find((endpoint) => endpoint.workspace === workspaceId && endpoint.id === endpointId);
}

export function getWorkspaceEntityKeysFromEndpointCatalog(workspaceId: WorkspaceId): EntityKey[] {
  const unique = new Set<EntityKey>();
  const entityKeys: EntityKey[] = [];

  listWorkspaceEndpoints(workspaceId).forEach((endpoint) => {
    if (!endpoint.entityKey) return;
    if (unique.has(endpoint.entityKey)) return;
    unique.add(endpoint.entityKey);
    entityKeys.push(endpoint.entityKey);
  });

  return entityKeys;
}
